spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uniquecode
    username: cuba
    password: cuba
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080